# Generated by Django 4.2.1 on 2023-05-25 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название обьекта', max_length=200, verbose_name='Название')),
                ('specialization', models.TextField(blank=True, help_text='Опишите специализацию обьекта', verbose_name='Специализация')),
                ('desc', models.TextField(blank=True, help_text='Введите описание площадки', verbose_name='Описание площадки')),
                ('address', models.CharField(max_length=12, verbose_name='Адрес объекта')),
                ('coordinates', models.CharField(max_length=12, verbose_name='Координаты объекта')),
                ('operating_hours', models.CharField(blank=True, max_length=12, verbose_name='Режим работы')),
                ('site', models.URLField(help_text='Введите сайт объекта', max_length=40, verbose_name='Сайт объекта')),
                ('area_sum', models.PositiveIntegerField(blank=True, help_text='Введите общую площадь имущественного комплекса (кв. м)', verbose_name='Общая площадь имущественного комплекса (кв. м)')),
                ('area_rent', models.PositiveIntegerField(blank=True, help_text='Введите свободную арендопригодную площадь (кв. м)', verbose_name='Свободная арендопригодная площадь (кв. м)')),
                ('features', models.TextField(blank=True, help_text='Напишите объекты коллективного пользования, спец. оборудование объектов и т.д. ', verbose_name='Особенности')),
                ('additional_information', models.TextField(blank=True, help_text='Введите важную по вашему мнению дополнительную информацию', verbose_name='Дополнительная информация')),
                ('capacity', models.CharField(blank=True, help_text='Введите вместимость обьекта (кол. людей)', max_length=200, verbose_name='Вместимость обьекта')),
                ('bookings', models.TextField(blank=True, help_text='Даты в которые объект занят', verbose_name='Даты бронирования')),
                ('cost', models.CharField(blank=True, help_text='Введите стоимость аренды', max_length=200, verbose_name='Стоимость')),
                ('owner', models.ForeignKey(help_text='Выберите контактное лицо/владельца обьекта', on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='users.landlord', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Обьекты',
                'ordering': ['-cost'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(help_text='Введите дату создания', verbose_name='Дата создания')),
                ('title', models.CharField(help_text='Введите заголовок новости', max_length=200, verbose_name='Заголовок')),
                ('news_full_text', models.TextField(help_text='Введите текст новости', verbose_name='Содержание')),
                ('news_video_link', models.URLField(blank=True, help_text='Вставьте ссылку на видео', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='BuildingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Выберите изображение', upload_to='building_images/%Y/%m/%d/', verbose_name='Изображение')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_images', to='buildings.building')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Дата начала аренды', verbose_name='Дата начала аренды')),
                ('check_out', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Дата окончания аренды', verbose_name='Дата окончания аренды')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='buildings.building')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='users.renterindividual', verbose_name='Арендатор')),
            ],
        ),
    ]
