# Generated by Django 4.2.1 on 2023-05-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='area_rent',
            field=models.PositiveIntegerField(blank=True, help_text='Введите свободную арендопригодную площадь (кв. м)', null=True, verbose_name='Свободная арендопригодная площадь (кв. м)'),
        ),
        migrations.AlterField(
            model_name='building',
            name='area_sum',
            field=models.PositiveIntegerField(blank=True, help_text='Введите общую площадь имущественного комплекса (кв. м)', null=True, verbose_name='Общая площадь имущественного комплекса (кв. м)'),
        ),
    ]
