# Generated by Django 4.2.1 on 2023-05-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_alter_building_area_rent_alter_building_area_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='cost',
            field=models.PositiveIntegerField(blank=True, help_text='Введите стоимость аренды за сутки', null=True, verbose_name='Стоимость'),
        ),
    ]
