# Generated by Django 4.2.1 on 2023-05-24 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='comments',
        ),
    ]
