# Generated by Django 4.2.1 on 2023-05-23 14:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='renterprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='contact_email'),
        ),
        migrations.AddField(
            model_name='renterprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='Формат номера телефона: +79999999999', regex='^\\+?7?\\d{8,8}$')]),
        ),
    ]
