# Generated by Django 4.2.1 on 2023-05-25 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlordprofile',
            name='adress',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес организации'),
        ),
        migrations.AlterField(
            model_name='landlordprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Контактный email'),
        ),
        migrations.AlterField(
            model_name='landlordprofile',
            name='inn',
            field=models.IntegerField(blank=True, null=True, verbose_name='ИНН организации'),
        ),
        migrations.AlterField(
            model_name='landlordprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='landlordprofile',
            name='organization_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Название организации'),
        ),
        migrations.AlterField(
            model_name='landlordprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[django.core.validators.RegexValidator(message='Формат номера телефона: +79999999999', regex='^\\+?7?\\d{10,10}$')], verbose_name='Контактный телефон'),
        ),
    ]
