# Generated by Django 4.2.1 on 2023-05-24 21:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_renterprofile_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlordprofile',
            name='adress',
            field=models.CharField(blank=True, max_length=300, verbose_name='Адрес организации'),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Контактный email'),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='inn',
            field=models.IntegerField(blank=True, default=1, verbose_name='ИНН организации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='organization_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='Название организации'),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='organization_type',
            field=models.CharField(blank=True, choices=[('IP', 'Индивидуальный предприниматель'), ('ORGANIZATION', 'Юридическое лицо')], max_length=50, verbose_name='Юридический статус'),
        ),
        migrations.AddField(
            model_name='landlordprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='Формат номера телефона: +79999999999', regex='^\\+?7?\\d{10,10}$')], verbose_name='Контактный телефон'),
        ),
        migrations.AddField(
            model_name='renterprofile',
            name='adress',
            field=models.CharField(blank=True, max_length=300, verbose_name='Адрес организации'),
        ),
        migrations.AddField(
            model_name='renterprofile',
            name='inn',
            field=models.IntegerField(blank=True, default=1, verbose_name='ИНН организации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='renterprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='renterprofile',
            name='organization_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='Название организации'),
        ),
        migrations.AddField(
            model_name='renterprofile',
            name='organization_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Физическое лицо'), ('IP', 'Индивидуальный предприниматель'), ('ORGANIZATION', 'Юридическое лицо')], default='INDIVIDUAL', max_length=50, verbose_name='Юридический статус'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Фамилия'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(default=1, max_length=100, verbose_name='Отчество'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='renterprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Контактный email'),
        ),
        migrations.AlterField(
            model_name='renterprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='Формат номера телефона: +79999999999', regex='^\\+?7?\\d{10,10}$')], verbose_name='Контактный телефон'),
        ),
    ]
