# Generated by Django 4.2.1 on 2023-05-22 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('objects', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='owner',
            field=models.ForeignKey(help_text='Выберите контактное лицо/владельца обьекта', on_delete=django.db.models.deletion.CASCADE, related_name='_objects', to='users.landlord', verbose_name='Владелец'),
        ),
    ]
